wcm-io-devops/conga-aem-definitions

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-author.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-publish.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher/author/vhost_author.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/_vhost_publish_shared_include.conf.hbs, example/src/main/environments/test.yaml
This PR adds Apache 2.4 compatibility with conditional statements.
To handle ip address and host based access control rules in Apache 2.4 the options
- dispatcher.allowFlushFromHost
- dispatcher.allowAdminAccessFromHost
were introduced for handling host based rules.
The existing options
- dispatcher.allowFlushFrom
- dispatcher.allowAdminAccessFrom
are used for ip based access control options.
=> Apache 2.4 compatibility

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-author.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-common.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-publish.yaml
As discussed: All roles should explicitly list all httpd modules they depend on for their configuration files, even if that means that the same module is activated multiple times.
=> Make each role explicitly activate all httpd modules it depends on.

.gitignore
Currently IntelliJ *.iml files are not ignored by Git
=> Properly ignore IntelliJ *.iml files

changes.xml, conga-aem-definitions/src/main/templates/aem-cms/start.hbs
I didn't make it optional since you never want AEM to fork beyond the Quickstart double-click usecase.
=> Start AEM with -nofork option

conga-aem-definitions/src/main/templates/aem-dispatcher/author/vhost_author.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/author/vhost_author.ssl.conf.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/_vhost_publish_shared_include.conf.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.ssl.conf.hbs
The invalidation URL should never be rewritten as the resulting redirect causes the flush to fail if the URL is requested with anything else but the primary hostname (which is often the case when internal IPs are used for communication between the hosts).
=> Exclude the dispatcher invalidation URL from rewriting.

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-author-dam-update-asset-workflow-minimal.json.hbs
Sadly I can't create branches, therefor a pull request :)
This change adds a configuration `minimalDamUpdateAssetWorkflowTransient` which defaults to true. If enabled, the Minimal Dam Update Asset Workflow is created as transient workflow in AEM.
Note: the Workflow Console does not care about this fact and show the Workflow as non-transient. But as soon as you open it, you can see, that the required flag is set.
=> Make Minimal 'Dam Update Asset' workflow transient

changes.xml, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-publish-slingmapping.json.hbs
Using "/" as the first search path improves the order of "realPathList" if the resource resolution has no match.
If no resource from the complete list of possible matches can be mapped to content (e.g. on a 404), the first generated resource path is returned. This currently adds "{slingMappingPath}" to the path. Assuming Dispatcher provides an non-shortened path, this path is better _not_ changed, or handlers working with it will have to cope with a path containing added path segments.
Relevant code in Sling: https://github.com/apache/sling/blob/6ec4eef74b1120d1eb15fe50f4e45497151b46e6/bundles/resourceresolver/src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverImpl.java#L370
=> Improve support for error handlers

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml
Changed default log format from combined to custom log format in order to remove ip format from access.log (due to data privacy issues).
=> Updated default access log format to not include client ip address

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.conf.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.ssl.conf.hbs
In a setup with a SSL Offloader the website is only served via http to the loadbalancer.
As de-facto standard the loadbalancer/offloader normally sends the "X-Forwarded-For: https" header.
To support this setup the following changes were implemented:
* Always add "Strict-Transport-Security" header when ssl is enforced
* The rewriteHomepageRedirect should directly redirect to the SSL hostname (since Apache is not running with SSL he will redirect to http://... otherwise)
* The rewritePrimaryHostname mechanism was adjusted to detect requests that were originally forwarded for https
=> Add compatibility for setups with SSL offloading

changes.xml, conga-aem-definitions/pom.xml, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-author-replicationagents.json.hbs, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-publish-replicationagents.json.hbs, example/pom.xml, example/src/main/environments/test-aem63.yaml
Dots in replication agent names currently lead to an exception in AEM since `.` is not allowed in agent names.
e.g.
```
- node: dev.website1.com
roles:
- role: aem-fe-archetype-aem-cms-combined
variant: aem-publish
config:
replication.publish.flushTarget:
name: ${node.replace(".","_")}
url: https://${node}
```
This PR depends on: https://github.com/wcm-io-devops/conga/pull/2
=>  Sanitize replication agent names by replacing dots with underscores

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml
The current cache settings for the aem-author dispatcher results in problems with cached pages in the administration section of AEM.
Adobe recommends to not cache anything in the author dispatcher (see https://helpx.adobe.com/experience-manager/dispatcher/using/dispatcher.html#UsingaDispatcherwithanAuthorServer) but i assume that caching js and css files of the clientlibs below /libs and /etc should be safe.
=> Restrict caching of aem-author instances

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher/author/vhost_author.conf.hbs
The functionality for publish instances was added with https://github.com/wcm-io-devops/conga-aem-definitions/pull/24, but I missed to update the author instances.
=> Add ssl offloading to aem-author dispatcher variants

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml
apply the publish sling mappings only on  instances with publish runmode
=> WDCONGA-22 apply the publish sling mappings only on  instances with publish runmode

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml
Introduced sling.mapping.generatePackage to allow disabling of the sling mapping package.
In some cases this is necessary, because otherwise the existing (legacy) sling mapping will be overwritten.
=> Role aem-cms: Introduce sling.mapping.generatePackage

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml
Our conga roles are using or are going to use a default stop timeout of 1200 seconds so we should increase this timeout here too. 180 seconds or 3 minutes was also a little bit too optimistic.
=> Role aem-cms: Increase default quickstart.stopTimeout to 1200 seconds.

changes.xml, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-publish-slingmapping.json.hbs
This reverts commit baf80f7aba11234f7a161369fa6eafdfb2b04705, reversing
changes made to 38661bd8060911365ca3bc724ee43119059b9ed9.
Reverts PR: https://github.com/wcm-io-devops/conga-aem-definitions/pull/40
=> Revert "Merge branch 'feature/WDCONGA-21-fix-sling-mappings' into develop

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-author-replicationagents.json.hbs, conga-aem-definitions/src/main/templates/aem-cms/aem-cms-publish-replicationagents.json.hbs
aliasUpdate is needed when the website uses sling:alias or vanity URLs. default: false
see https://helpx.adobe.com/experience-manager/6-5/sites/deploying/using/replication.html#ConfiguringaDispatcherFlushagent
=> Dispatcher Flush Agen: add `aliasUpdate` flag 

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.partials.hbs, example/src/main/environments/test-aem63.yaml, example/src/main/environments/test.yaml
This enables you to configure multiple Cache-Control headers for various locations.
=> Add httpd.headers.cacheControl to aem-dispatcher role

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher-ams/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs
Modern browsers use Requests that include the "Range" Header to stream videos. This does not work with gzip, therefor video formats need to be excluded from gzip.
=> Don't compress mp4 / webm videos as this prevents streaming

changes.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml, conga-aem-definitions/src/main/templates/aem-cms/start.hbs, example/src/main/environments/test-aem63.yaml, example/src/main/environments/test.yaml
As discussed this setting was never set correctly in our environments and thus had no effect and can be removed.
=> Role: aem-cms: Remove "jvm.path" configuration option

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-ams.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml
The current example in the dispatcher roles is misleading because `cloudManagerConditional` expects a dictionary and not a list. It is correctly used in the [examples](https://github.com/wcm-io-devops/conga-aem-definitions/blob/develop/example/src/main/environments/test.yaml#L307), though.
=> Use dict instead of list for cloudManagerConditional

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs
When using `httpd.rootRedirect.url` in AEMaaCS, you get one unnecessary 301 redirect:
```
$ curl -IL http://aemaacs.example.com
HTTP/1.0 301 Moved Permanently
Retry-After: 0
Location: https://aemaacs.example.com/  # first SSL upgrade - fine
[...]
HTTP/1.0 200 Connection established
HTTP/2 301
location: http://aemaacs.example.com/demo.html  # this one is unnecessary - we were already on an HTTPS connection
[...]
HTTP/1.0 301 Moved Permanently
Retry-After: 0
Location: https://aemaacs.example.com/demo.html  # final page
[...]
HTTP/2 200
[...]
```
Since there is no possibility to host a non-SSL VHost on AEMaaCS (you can't even add a domain when there's no SSL certificate present that covers it), the redirect to the HTTP version of the VHost is not necessary. The fix in this PR leads to this …
=> Set httpd.rootRedirect.url to HTTPS version of VHost

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml
Explicitly assign a prefix "9999_" in enabled_vhosts to ensure this host is picked last.
=> Role aem-dispatcher-cloud: Add back symlink of "default.host" which was removed in 1.11.2.

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher/author/vhost_author.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.partials.hbs
I noticed that the IfModule statement did not work the way it was designed.
Also the remote ip configuration should be possible in author vhosts (since there a valid client ip is required for several ip secured areas)
=> Role aem-dispatcher: Fix / Enhance remoteip functionality

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-ams.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher-ams/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher/publish/vhost_publish_tenant.partials.hbs, example/src/main/environments/test.yaml
This enhances #77 because the Permissions-Policy is currently not supported everywhere and the `Feature-Policy` is the predecessor of the `Permissions-Policy` header.
=> Introduce httpd.headers.featurePolicy Header

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher-ams/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs
With the current solution we are sending duplicate headers when for example `sling.additional.response.headers` is configured to send X-Frame-Options.
Since `setifempty` is only possible with httpd/apache 2.4.7+ I decided to just overwrite the header with our desired value.
=> Role aem-dispatcher-ams, aem-dispatcher-cloud fix duplicate X-Frame-Options header

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-ams.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher.yaml
With #83 we moved deny rules to the new `dispatcher.filterAppend` list in order to implement a solution for blocking the form validator bypass issue with #84.
The problem with that solution is that it forces the users of the conga-aem-definitions to reallow for example form posts in the `filterAppend` which then also would make it necessary to readd the fix for the form validator bypass at the end of the customized `filterAppend` list.
From my perspective it makes more sense to only add the fix for the validator bypass to the filterAppend list and keep the other filters as they are.
=> Revert dispatcher.filter filter list to values from 1.13.0

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, example/src/main/environments/test.yaml
With #58 we introduced the aem-dispatcher-ams role and this PR ports the functionality to disable the available and enabled vhost.
=> Role aem-dispatcher-cloud: Introduce httpd.generateAvailableVhost and httpd.generateEnabledVhost to control vhost generation.

changes.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs, example/src/main/environments/test.yaml
This PR ports the `httpd.rewriteIncludes` from the aem-dispatcher-ams role (added with #58) to the aem-dispatcher-cloud role
=> Role aem-dispatcher-cloud: Introduce httpd.rewriteIncludes

changes.xml, conga-aem-definitions/pom.xml, conga-aem-definitions/src/main/roles/aem-dispatcher-ams.yaml, conga-aem-definitions/src/main/roles/aem-dispatcher-cloud.yaml, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/variables/global.vars.hbs, example/pom.xml, example/src/main/environments/test.yaml, parent/pom.xml, pom.xml
* Role `aem-dispatcher-cloud`: Add `httpd.headers.htmlExpirationTimeSec` parameter to control the default expiration time for text/html responses.
* Role `aem-dispatcher-cloud`: Remove `httpd.headers.htmlExpirationTimeMin` parameter which was interpreted incorrectly as seconds instead of minutes. Build will fail if this parameters is still in use.
* also remove `httpd.headers.htmlExpirationTimeMin` from role `aem-dispatcher-ams` which was never used.
Depends on https://github.com/wcm-io-devops/conga/pull/33
=> Introduce httpd.headers.htmlExpirationTimeSec as replacement of httpd.headers.htmlExpirationTimeMin

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs
When not specifying the protocol there will be an unnecessary redirect to http first before upgrading again to https.
This happens because the dispatcher is serving requests using http.
=> Role aem-dispatcher-cloud: Use https in rewriteHomepageRedirect

changes.xml, conga-aem-definitions/src/main/templates/aem-dispatcher-ams/conf.d/available_vhosts/tenant.vhost.partials.hbs, conga-aem-definitions/src/main/templates/aem-dispatcher-cloud/conf.d/available_vhosts/tenant.vhost.partials.hbs
Generate the value of the debugging header X-Vhost with discriminable values.
=> Dynamically generate X-VHost header

changes.xml, conga-aem-definitions/pom.xml, conga-aem-definitions/src/main/roles/aem-cms.yaml, example/pom.xml
the order of installation is not relevant for those packages
depends on https://github.com/wcm-io-devops/conga-aem-plugin/pull/179
=> Role aem-cms: Mark all content packages that might be generated with dependencyChainIgnore=true
